wandb_version: 1

cem_alpha:
  value: 0.95
cem_num_elites:
  value: 16
cem_num_iters:
  value: 4
mpc_discount:
  value: 0.99
mpc_horizon_steps:
  value: 50
mpc_num_action_sequences:
  value: 200
mpc_strategy:
  value: cem
mpc_timestep:
  value: 0.05
