wandb_version: 1

cem_alpha:
  desc: null
  value: 0.99
cem_num_elites:
  desc: null
  value: 32
cem_num_iters:
  desc: null
  value: 16
mpc_discount:
  desc: null
  value: 0.8
mpc_horizon_steps:
  desc: null
  value: 1
mpc_num_action_sequences:
  desc: null
  value: 500
mpc_strategy:
  desc: null
  value: cem
mpc_timestep:
  desc: null
  value: 0.05
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701981928.597408
    t:
      1:
      - 1
      - 12
      - 55
      2:
      - 1
      - 12
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.18
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
