wandb_version: 1

cem_alpha:
  value: 0.8
cem_num_elites:
  value: 32
cem_num_iters:
  value: 2
mpc_discount:
  value: 0.8
mpc_horizon_steps:
  value: 50
mpc_num_action_sequences:
  value: 2000
mpc_strategy:
  value: cem
mpc_timestep:
  value: 0.05
